# Generated by Django 5.2.7 on 2025-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0006_transaction_expiry_transaction_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Add Money', 'Add Money'), ('Data Purchase', 'Data Purchase'), ('Airtime Purchase', 'Airtime Purchase')], max_length=20),
        ),
    ]
