# Generated by Django 5.2.7 on 2025-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0008_transaction_account_number_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Add Money', 'Add Money'), ('Data Purchase', 'Data Purchase'), ('Airtime Purchase', 'Airtime Purchase'), ('Bill Payment', 'Bill Payment'), ('Betting', 'Betting')], max_length=20),
        ),
    ]
