# Generated by Django 5.2.7 on 2025-11-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0009_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='planLabel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
