# Generated by Django 5.2.7 on 2025-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0010_transaction_planlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Add Money', 'Add Money'), ('Data Purchase', 'Data Purchase'), ('Airtime Purchase', 'Airtime Purchase'), ('Bill Payment', 'Bill Payment'), ('Betting', 'Betting'), ('Reward Points', 'Reward Points'), ('Reward Redemption', 'Reward Redemption')], max_length=20),
        ),
    ]
