# Generated by Django 5.2.7 on 2025-12-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0011_transaction_points_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='planLabel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
