# Generated by Django 5.2.7 on 2025-12-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0012_remove_transaction_planlabel_remove_user_profilepic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='plan_label',
            new_name='planLabel',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profilePic',
        ),
    ]
