# Generated by Django 5.2.7 on 2025-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdave_app', '0013_rename_plan_label_transaction_planlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flw_currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flw_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flw_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flw_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flw_tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
